### ISSUE TITLE
Update for latest VS Code

### ISSUE THREAD

**Issue by Christian-Seematter** [smkamranqadri/vscode-bolt-language#1]
Hey @smkamranqadri!

I found this nifty package in the extension manager and thought I'd give it a try. Cool that you are providing this! Autocomplete works fine, however the syntax highlighting does only for commented lines:
![2016-11-24 20_17_46-test bolt - hazuapp - visual studio code](https://cloud.githubusercontent.com/assets/1957259/20608619/b2cfb770-b283-11e6-9d5c-30003a4e59f0.png)

Looking forward to hear if you might pick this project back up.

**Comment by florent1933** [comment]
Same for me. I think, we need to do a PR.

**Comment by smkamranqadri** [comment]
@florent1933  That would be great

**Comment by smkamranqadri** [comment]
fixed it and published the new version.

**Comment by bpinney** [comment]
I noticed there are no new commits to the repo on github.  Will you be pushing to github soon?

**Comment by smkamranqadri** [comment]
Just pushed.
