### ISSUE TITLE
Support nesting paths

### ISSUE THREAD

**Issue by dinoboff** [smkamranqadri/vscode-bolt-language#3]
Can you add support for [nested path](https://github.com/firebase/bolt/blob/master/samples/children.bolt)?

**Comment by smkamranqadri** [comment]
Sure, I will look into it.

**Comment by esprehn** [comment]
Any luck here? This makes it hard to edit a lot of rule files.

**Comment by smkamranqadri** [comment]
Not yet, will look into by tomorrow.

**Comment by smkamranqadri** [comment]
The issue is resolved in last version.
![Screenshot 2023-10-21 at 1 23 20 AM](https://github.com/smkamranqadri/vscode-bolt-language/assets/13115396/a2c0e1e8-35f8-4d4a-8796-185764c8dc8e)
